import type { Metadata } from 'next';
import { Header } from '@/components';
import { ToastContainer } from 'react-toastify';
import '../styles/index.sass';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

interface Props {
    children: React.ReactNode;
}

const RootLayout = ({ children }: Props) => {
    return (
        <html lang='en'>
            <body>
                <Header />
                <main>{children}</main>
                <ToastContainer position='bottom-right' />
            </body>
        </html>
    );
};

export default RootLayout;
